# We'll modify it when we push the repository to the
# website we want to switch to.
baseURL = "http://example.org/"
languageCode = "en-us"
name = "gouthamkrishnakv"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
contentDir = "content"
## --- ALL PARAMETERS NEEDED FOR THE PORTFOLIO ---
[params]
title = "Goutham Krishna K V"
author = "Goutham Krishna K V"
profilePicture = "images/PROFILE.jpg"
mainSections = ["home","post", "contact"]

## -- ALL SOCIAL MEDIA HANDLES --
# - Twitter
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/gautham9991"
# - LinkedIn
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/gauthamkrishna9991/"
# - Telegram
[[params.socialIcons]]
icon = "fab fa-telegram"
title = "Telegram"
url = "https://t.me/gauthamkrishna9991"

# - GitHub
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://www.github.com/gouthamkrishnakv"
# - GitLab
[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/gauthamkrishna9991"
